 (define-abbrev-table 'define-abbrev-table '(
    ))

(define-abbrev-table 'jde-mode-abbrev-table '(
    ))

(define-abbrev-table 'idl-mode-abbrev-table '(
    ))

(define-abbrev-table 'java-mode-abbrev-table '(
    ("na" "native" nil 0)
    ("fl" "float" nil 0)
    ("sh" "short" nil 0)
    ("fi" "final" nil 0)
    ("im" "import" nil 0)
    ("pu" "public" nil 0)
    ("vo" "void" nil 0)
    ("pr" "private" nil 0)
    ("do" "double" nil 0)
    ("bo" "boolean" nil 0)
    ("re" "return" nil 0)
    ("st" "string" nil 0)
    ("cl" "class" nil 0)
    ("us" "using" nil 0)
    ("vi" "virtual" nil 0)
    ("ov" "override" nil 0)
    ("con" "continue" nil 0)
    ("ext" "extends" nil 0)
    ("sta" "static" nil 0)
    ("imp" "implements" nil 0)
    ("tos" "toString" nil 0)
    ("syn" "synchronized" nil 0)
    ("pro" "protected" nil 0)    
    ("ve" "Vector" nil 0)
    ("ob" "Object" nil 0)
    ("sy" "System.Console.WriteLine(" nil 0)
    ("th" "throws" nil 0)
    ("ins" "instanceof" nil 0)
    ("el" "else" nil 0)
    ("nu" "null" nil 0)
    ("ex" "Exception" nil 0)
    ("wh" "while" nil 0)
    ("tr" "true" nil 0)
    ("fa" "false" nil 0)
    ("dim" "Dimension" nil 0)    
    ("sub" "substring" nil 0)
    ("le" "length" nil 0)
    ("wi" "width" nil 0)
    ("he" "height" nil 0)
    ("po" "Point" nil 0)
    ("sw" "sw" nil 0)
    ("gr" "Graphics" nil 0)
    ("rec" "Rectangle" nil 0)
    ("di" "dimension" nil 0)
    ("r" "r" nil 0)
    ("iox" "IOException" nil 0)
    ))

(define-abbrev-table 'objc-mode-abbrev-table '(
    ))

(define-abbrev-table 'cperl-mode-abbrev-table '(
    ("!p" "#!/usr/bin/perl" nil 0)     
    ("pr" "print" nil 0)     
    ("th" "$this->" nil 0)     
    ("wh" "while" nil 0)     
    ("fr" "foreach" nil 0)     
    ("el" "else" nil 0)     
    ("sp" "split" nil 0)
    ("re" "return" nil 0)
    ("sh" "shift" nil 0)
    ("pac" "package" nil 0)
    ("def" "defined" nil 0)
    ))

(define-abbrev-table 'c++-mode-abbrev-table '( 
    ("inc" "#include" nil 0)
    ("nam" "namespace" nil 0)
    ("Ser" "ServiceLib" nil 0)
    ("def" "#define" nil 0)
    ("sw" "switch" nil 0)
    ("pri" "printf(" nil 0)    
    ("wh" "while" nil 0)
    ("bo" "bool" nil 0)
    ("co" "const" nil 0)
    ("lo" "long" nil 0)
    ("vi" "virtual" nil 0)
    ("cl" "class" nil 0)
    ("te" "template" nil 0)
    ("pr" "private" nil 0)
    ("fr" "friend" nil 0)
    ("pu" "public" nil 0)
    ("op" "operator" nil 0)
    ("ch" "char" nil 0)
    ("st" "String" nil 0)
    ("sta" "static" nil 0)
    ("fl" "float" nil 0)
    ("re" "return" nil 0)
    ("vo" "void" nil 0)
    ("de" "#define" nil 0)
    ("en" "#endif" nil 0)
    ("ifn" "#ifndef" nil 0)
    ("ifd" "#ifdef _DEBUG_" nil 0)
    ("typ" "typedef" nil 0)
    ("el" "else" nil 0)
    ("uns" "unsigned" nil 0)
    ("fa" "false" nil 0)
    ("tr" "true" nil 0)
    ("un" "union" nil 0)
    ("con" "continue" nil 0)
    ("re" "return" nil 0)
    ))

(define-abbrev-table 'c-mode-abbrev-table '(		     
    ("le" "level" nil 0)
    ("nr" "numberOfRepeats" nil 0)
    ("ff" "fflush(stdout)" nil 0)
    ("lo" "long" nil 0)
    ("con" "continue" nil 0)
    ("av" "available" nil 0)
    ("soc" "sockaddr_in" nil 0)
    ("s" "s" nil 0)
    ("so" "so" nil 0)
    ("sw" "switch" nil 0)
    ("ch" "char" nil 0)
    ("st" "String" nil 0)
    ("inc" "#include" nil 0)
    ("br" "br" nil 0)
    ("sta" "static" nil 0)
    ("fl" "float" nil 0)
    ("soc" "sockaddr_in" nil 0)
    ("re" "return" nil 0)
    ("vo" "void" nil 0)
    ("de" "#define" nil 0)
    ("pr" "printf(" nil 0)
    ("en" "#endif" nil 0)
    ("ifn" "#ifndef" nil 0)
    ("ifd" "#ifdef _DEBUG_" nil 0)
    ("typ" "typedef" nil 0)
    ("el" "else" nil 0)
    ("uns" "unsigned" nil 0)
    ("wh" "while" nil 0)
    ))

(define-abbrev-table 'text-mode-abbrev-table '(
    ))

(define-abbrev-table 'lisp-mode-abbrev-table '(
    ))

(define-abbrev-table 'help-mode-abbrev-table '(
    ))

(define-abbrev-table 'completion-list-mode-abbrev-table '(
    ))

(define-abbrev-table 'fundamental-mode-abbrev-table '(
    ))

(define-abbrev-table 'global-abbrev-table '(
    ("deb" "debug" nil 0)
    ))

